=== vulndb/data/schema.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "type": "object",
  "title": "Vulnerability schema",
  "description": "This schema describes json format for vulnerability",
  "definitions": {
    "multiString": {
      "oneof": [
        {
          "type": "string",
          "maxLength": 90,
          "minLength": 30
        },
        {
          "type": "array",
          "minItems": 1,
          "items": {
            "type": "string",
            "maxLength": 90
          }
        }
      ]
    }
  },
  "properties": {
    "id": {
      "type": "integer",
      "title": "Vulnerability unique id",
      "minimum": 1
    },
    "title": {
      "type": "string",
      "title": "Vulnerability title",
      "minLength": 4,
      "maxLength": 255
    },
    "description": {
      "title": "A very long description for vulnerability",
      "$ref": "#/definitions/multiString"
    },
    "severity": {
      "type": "string",
      "title": "Vulnerability severity",
      "enum": [
        "high",
        "medium",
        "low",
        "informational"
      ]
    },
    "wasc": {
      "type": "array",
      "title": "WASC identifiers",
      "description": "http://projects.webappsec.org/w/page/13246974/Threat%20Classification%20Reference%20Grid",
      "uniqueItems": true,
      "minItems": 1,
      "items": {
        "type": "string",
        "minLength": 1
      }
    },
    "tags": {
      "type": "array",
      "uniqueItems": true,
      "minItems": 1,
      "items": {
        "type": "string",
        "minLength": 2,
        "maxLength": 255
      }
    },
    "cwe": {
      "type": "array",
      "title": "CWE indentifiers",
      "description": "https://cwe.mitre.org/data/index.html",
      "uniqueItems": true,
      "items": {
        "type": "string",
        "minLength": 1
      }
    },
    "owasp_top_10": {
      "type": "object",
      "description": "position in owasp top ten splitted by years",
      "patternProperties": {
        "^[12][0-9]{3}$": {
          "type": "array",
          "minItems": 1,
          "items": {
            "type": "integer",
            "minimum": 1
          }
        }
      },
      "additionalProperties": false
    },
    "fix": {
      "type": "object",
      "properties": {
        "guidance": {
          "$ref": "#/definitions/multiString",
          "title": "A very long text explaining how to fix the vulnerability"
        },
        "effort": {
          "type": "integer",
          "minimum": 0
        }
      },
      "required": [
        "guidance",
        "effort"
      ]
    },
    "references": {
      "type": "array",
      "minItems": 1,      
      "items": {
        "type": "object",
        "properties": {
          "url": {
            "type": "string",
            "format": "uri"
          },
          "title": {
            "type": "string",
            "minLength": 4,
            "maxLength": 255
          }
        },
        "required": [
          "url",
          "title"
        ]
      }
    }
  },
  "required": [
    "id",
    "title",
    "description",
    "severity",
    "fix"
  ]
}

=== vulndb/data/db/30-ldap-injection.json
{
  "id": 30, 
  "title": "LDAP Injection", 
  "severity": "high", 
  "description": [
    "Lightweight Directory Access Protocol (LDAP) is used by web", 
    "applications to access and maintain directory information services.", 
    "One of the most common uses for LDAP is to provide a Single-Sign-On", 
    "(SSO) service that will allow clients to authenticate with a web site", 
    "without any interaction (assuming their credentials have been", 
    "validated by the SSO provider).\n\nLDAP injection occurs when untrusted", 
    "data is used by the web application to query the LDAP directory", 
    "without prior sanitisation.\n\nThis is a serious security risk, as it", 
    "could allow cyber-criminals the ability to query, modify, or remove", 
    "anything from the LDAP tree. It could also allow other advanced", 
    "injection techniques that perform other more serious attacks.\n\nThe tool", 
    "was able to detect a page that is vulnerable to LDAP injection based", 
    "on known error messages."
  ], 
  "fix": {
    "effort": 50, 
    "guidance": [
      "It is recommended that untrusted data is never used to form a LDAP", 
      "query.\n\nTo validate data, the application should ensure that the", 
      "supplied value contains only the characters that are required to", 
      "perform the required action. For example, where a username is", 
      "required, then no non-alphanumeric characters should be accepted.\n\nIf", 
      "this is not possible, special characters should be escaped so they are", 
      "treated accordingly. The following characters should be escaped with a", 
      "`\\`:\n\n* `&` * `!` * `|` * `=` * `<` * `>` * `,` * `+` * `-` * `\"` *", 
      "`'` * `;`\n\nAdditional character filtering must be applied to:\n\n* `(` *", 
      "`)` * `\\` * `/` * `*` * `NULL`\n\nThese characters require ASCII", 
      "escaping."
    ]
  }, 
  "tags": [
    "ldap", 
    "injection", 
    "regexp"
  ], 
  "references": [
    {
      "url": "http://projects.webappsec.org/w/page/13246947/LDAP-Injection", 
      "title": "WASC"
    }, 
    {
      "url": "https://www.owasp.org/index.php/LDAP_injection", 
      "title": "OWASP"
    }
  ]
}

=== vulndb/data/db/22-httponly-cookie.json
{
  "id": 22, 
  "title": "HttpOnly cookie", 
  "severity": "informational", 
  "description": [
    "HTTP by itself is a stateless protocol. Therefore the server is unable", 
    "to determine which requests are performed by which client, and which", 
    "clients are authenticated or unauthenticated.\n\nThe use of HTTP cookies", 
    "within the headers, allows a web server to identify each individual", 
    "client and can therefore determine which clients hold valid", 
    "authentication, from those that do not. These are known as session", 
    "cookies.\n\nWhen a cookie is set by the server (sent the header of an", 
    "HTTP response) there are several flags that can be set to configure", 
    "the properties of the cookie and how it is to be handled by the", 
    "browser.\n\nThe `HttpOnly` flag assists in the prevention of client", 
    "side-scripts (such as JavaScript) accessing and using the cookie.", 
    "This can help prevent XSS attacks targeting the cookies holding the", 
    "client's session token (setting the `HttpOnly` flag does not prevent,", 
    "nor safeguard against XSS vulnerabilities themselves)."
  ], 
  "fix": {
    "effort": 50, 
    "guidance": [
      "The initial step to remedy this would be to determine whether any", 
      "client-side scripts (such as JavaScript) need to access the cookie and", 
      "if not, set the `HttpOnly` flag.\n\nAdditionally, it should be noted", 
      "that some older browsers are not compatible with the `HttpOnly` flag,", 
      "and therefore setting this flag will not protect those clients against", 
      "this form of attack."
    ]
  }, 
  "references": [
    {
      "url": "https://www.owasp.org/index.php/HttpOnly", 
      "title": "HttpOnly - OWASP"
    }
  ]
}

=== vulndb/data/db/54-xpath-injection.json
{
  "id": 54, 
  "title": "XPath Injection", 
  "severity": "high", 
  "description": [
    "XML Path Language (XPath) queries are used by web applications for", 
    "selecting nodes from XML documents. Once selected, the value of these", 
    "nodes can then be used by the application.\n\nA simple example for the", 
    "use of XML documents is to store user information. As part of the", 
    "authentication process, the application will perform an XPath query to", 
    "confirm the login credentials and retrieve that user's information to", 
    "use in the following request.\n\nXPath injection occurs where untrusted", 
    "data is used to build XPath queries.\n\nCyber-criminals may abuse this", 
    "injection vulnerability to bypass authentication, query other user's", 
    "information, or, if the XML document contains privileged user", 
    "credentials, allow the cyber-criminal to escalate their privileges.", 
    "The tool injected special XPath query characters into the page and", 
    "based on the responses from the server, has determined that the page", 
    "is vulnerable to XPath injection."
  ], 
  "fix": {
    "effort": 50, 
    "guidance": [
      "The preferred way to protect against XPath injection is to utilise", 
      "parameterized (also known as prepared) XPath queries. When utilising", 
      "this method of querying the XML document any value supplied by the", 
      "client will be handled as a string rather than part of the XPath", 
      "query.\n\nAn alternative to parameterized queries it to use precompiled", 
      "XPath queries. Precompiled XPath queries are not generated dynamically", 
      "and will therefor never process user supplied input as XPath."
    ]
  }, 
  "cwe": ["91", "643"],
  "owasp_top_10": {"2013": [1]},
  "tags": [
    "web",
    "xpath", 
    "database", 
    "error", 
    "injection"
  ], 
  "references": [
    {
      "url": "http://projects.webappsec.org/w/page/13247005/XPath%20Injection", 
      "title": "WASC"
    }, 
    {
      "url": "https://www.owasp.org/index.php/XPATH_Injection", 
      "title": "OWASP"
    }
  ]
}

=== vulndb/data/db/17-file-inclusion.json
{
  "id": 17, 
  "title": "File Inclusion", 
  "severity": "high", 
  "description": [
    "Web applications occasionally use parameter values to store the", 
    "location of a file which will later be required by the server.\n\nAn", 
    "example of this is often seen in error pages, where the actual file", 
    "path for the error page is stored in a parameter value -- for example", 
    "`example.com/error.php?page=404.php`.\n\nA file inclusion occurs when", 
    "the parameter value (ie. path to file) can be substituted with the", 
    "path of another resource on the same server, effectively allowing the", 
    "displaying of arbitrary, and possibly restricted/sensitive, files.", 
    "The tool discovered that it was possible to substitute a parameter", 
    "value with another resource and have the server return the contents of", 
    "the resource to the client within the response."
  ], 
  "fix": {
    "effort": 50, 
    "guidance": [
      "It is recommended that untrusted data is never used to form a file", 
      "location to be included.\n\nTo validate data, the application should", 
      "ensure that the supplied value for a file is permitted. This can be", 
      "achieved by performing whitelisting on the parameter value, by", 
      "matching it against a list of permitted files. If the supplied value", 
      "does not match any value in the whitelist, then the server should", 
      "redirect to a standard error page.\n\nIn some scenarios, where dynamic", 
      "content is being requested, it may not be possible to perform", 
      "validation against a list of trusted resources, therefore the list", 
      "must also become dynamic (updated as the files change), or perform", 
      "filtering to remove extraneous user input (such as semicolons, periods", 
      "etc.) and only permit `a-z0-9`.\n\nIt is also advised that sensitive", 
      "files are not stored within the web root and that the user permissions", 
      "enforced by the directory are correct."
    ]
  }, 
  "tags": [
    "web",
    "file", 
    "inclusion", 
    "error", 
    "injection"
  ], 
  "references": [
    {
      "url": "https://www.owasp.org/index.php/PHP_File_Inclusion", 
      "title": "OWASP"
    }
  ]
}

=== vulndb/data/db/45-sql-injection.json
{
  "id": 45, 
  "title": "SQL Injection", 
  "severity": "high", 
  "description": [
    "Due to the requirement for dynamic content of today's web", 
    "applications, many rely on a database backend to store data that will", 
    "be called upon and processed by the web application (or other", 
    "programs). Web applications retrieve data from the database by using", 
    "Structured Query Language (SQL) queries.\n\nTo meet demands of many", 
    "developers, database servers (such as MSSQL, MySQL, Oracle etc.) have", 
    "additional built-in functionality that can allow extensive control of", 
    "the database and interaction with the host operating system itself.", 
    "An SQL injection occurs when a value originating from the client's", 
    "request is used within a SQL query without prior sanitisation. This", 
    "could allow cyber-criminals to execute arbitrary SQL code and steal", 
    "data or use the additional functionality of the database server to", 
    "take control of more server components.\n\nThe successful exploitation", 
    "of a SQL injection can be devastating to an organisation and is one of", 
    "the most commonly exploited web application vulnerabilities.\n\nThis", 
    "injection was detected as the tool was able to cause the server to", 
    "respond to the request with a database related error."
  ], 
  "fix": {
    "effort": 50, 
    "guidance": [
      "The only proven method to prevent against SQL injection attacks while", 
      "still maintaining full application functionality is to use", 
      "parameterized queries (also known as prepared statements). When", 
      "utilising this method of querying the database, any value supplied by", 
      "the client will be handled as a string value rather than part of the", 
      "SQL query.\n\nAdditionally, when utilising parameterized queries, the", 
      "database engine will automatically check to make sure the string being", 
      "used matches that of the column. For example, the database engine will", 
      "check that the user supplied input is an integer if the database", 
      "column is configured to contain integers."
    ]
  }, 
  "cwe": ["89"],
  "owasp_top_10": {"2013": [1]},
  "tags": [
    "web",
    "sql", 
    "injection", 
    "database", 
    "error"
  ], 
  "references": [
    {
      "url": "http://www.securiteam.com/securityreviews/5DP0N1P76E.html", 
      "title": "SecuriTeam"
    }, 
    {
      "url": "http://en.wikipedia.org/wiki/SQL_injection", 
      "title": "Wikipedia"
    }, 
    {
      "url": "https://www.owasp.org/index.php/SQL_Injection", 
      "title": "OWASP"
    }, 
    {
      "url": "http://projects.webappsec.org/w/page/13246963/SQL%20Injection", 
      "title": "WASC"
    }, 
    {
      "url": "http://www.w3schools.com/sql/sql_injection.asp", 
      "title": "W3 Schools"
    }, 
    {
      "url": "http://unixwiz.net/techtips/sql-injection.html", 
      "title": "UnixWiz"
    }
  ]
}

=== vulndb/data/db/36-operating-system-command-injection.json
{
  "id": 36, 
  "title": "Operating system command injection", 
  "severity": "high", 
  "description": [
    "To perform specific actions from within a web application, it is", 
    "occasionally required to run Operating System commands and have the", 
    "output of these commands captured by the web application and returned", 
    "to the client.\n\nOS command injection occurs when user supplied input", 
    "is inserted into one of these commands without proper sanitisation and", 
    "is then executed by the server.\n\nCyber-criminals will abuse this", 
    "weakness to perform their own arbitrary commands on the server. This", 
    "can include everything from simple `ping` commands to map the internal", 
    "network, to obtaining full control of the server.\n\nThe tool was able to", 
    "inject specific Operating System commands and have the output from", 
    "that command contained within the server response. This indicates that", 
    "proper input sanitisation is not occurring."
  ], 
  "fix": {
    "effort": 50, 
    "guidance": [
      "It is recommended that untrusted data is never used to form a command", 
      "to be executed by the OS.\n\nTo validate data, the application should", 
      "ensure that the supplied value contains only the characters that are", 
      "required to perform the required action.\n\nFor example, where the form", 
      "field expects an IP address, only numbers and periods should be", 
      "accepted. Additionally, all control operators (`&`, `&&`, `|`, `||`,", 
      "`$`, `\\`, `#`) should be explicitly denied and never accepted as valid", 
      "input by the server."
    ]
  }, 
  "tags": [
    "web",
    "os", 
    "command", 
    "code", 
    "injection",
    "error"
  ], 
  "references": [
    {
      "url": "http://projects.webappsec.org/w/page/13246950/OS%20Commanding", 
      "title": "WASC"
    }, 
    {
      "url": "https://www.owasp.org/index.php/OS_Command_Injection", 
      "title": "OWASP"
    }
  ]
}

=== vulndb/data/db/12-credit-card-number-disclosure.json
{
  "id": 12, 
  "title": "Credit card number disclosure", 
  "severity": "medium", 
  "description": [
    "Credit card numbers are used in applications where a user is able to", 
    "purchase goods and/or services.\n\nA credit card number is a sensitive", 
    "piece of information and should be handled as such. Cyber-criminals", 
    "will use various methods to attempt to compromise credit card", 
    "information that can then be used for fraudulent purposes.\n\nThrough", 
    "the use of regular expressions and CC number format validation,", 
    "It was possible to discover a credit card number located within the", 
    "affected page."
  ], 
  "fix": {
    "effort": 50, 
    "guidance": [
      "Initially, the credit card number within the response should be", 
      "checked to ensure its validity, as it is possible that the regular", 
      "expression has matched on a similar number with no relation to a real", 
      "credit card.\n\nIf the response does contain a valid credit card number,", 
      "then all efforts should be taken to remove or further protect this", 
      "information. This can be achieved by removing the credit card number", 
      "altogether, or by masking the number so that only the last few digits", 
      "are present within the response. (eg. _**********123_).\n\nAdditionally,", 
      "credit card numbers should not be stored by the application, unless", 
      "the organisation also complies with other security controls as", 
      "outlined in the Payment Card Industry Data Security Standard (PCI-", 
      "DSS)."
    ]
  }, 
  "cwe": ["200"],
  "references": [
    {
      "url": "http://en.wikipedia.org/wiki/Luhn_algorithm", 
      "title": "Wikipedia - Luhn algorithm"
    }, 
    {
      "url": "http://en.wikipedia.org/wiki/Bank_card_number", 
      "title": "Wikipedia - Bank card number"
    }
  ]
}

=== vulndb/data/db/38-password-field-with-auto-complete.json
{
  "id": 38, 
  "title": "Password field with auto-complete", 
  "severity": "low", 
  "description": [
    "In typical form-based web applications, it is common practice for", 
    "developers to allow `autocomplete` within the HTML form to improve the", 
    "usability of the page. With `autocomplete` enabled (default), the", 
    "browser is allowed to cache previously entered form values.\n\nFor", 
    "legitimate purposes, this allows the user to quickly re-enter the same", 
    "data when completing the form multiple times.\n\nWhen `autocomplete` is", 
    "enabled on either/both the username and password fields, this could", 
    "allow a cyber-criminal with access to the victim's computer the", 
    "ability to have the victim's credentials automatically entered as the", 
    "cyber-criminal visits the affected page.\n\nThe tool has discovered that", 
    "the affected page contains a form containing a password field that has", 
    "not disabled `autocomplete`."
  ], 
  "fix": {
    "effort": 50, 
    "guidance": [
      "The `autocomplete` value can be configured in two different locations.", 
      "The first and most secure location is to disable the `autocomplete`", 
      "attribute on the `<form>` HTML tag. This will disable `autocomplete`", 
      "for all inputs within that form. An example of disabling", 
      "`autocomplete` within the form tag is `<form autocomplete=off>`.\n\nThe", 
      "second slightly less desirable option is to disable the `autocomplete`", 
      "attribute for a specific `<input>` HTML tag. While this may be the", 
      "less desired solution from a security perspective, it may be preferred", 
      "method for usability reasons, depending on size of the form. An", 
      "example of disabling the `autocomplete` attribute within a password", 
      "input tag is `<input type=password autocomplete=off>`."
    ]
  }
}
