=== vulndb/data/schema.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "type": "object",
  "title": "Vulnerability schema",
  "description": "This schema describes json format for vulnerability",
  "definitions": {
    "multiString": {
      "oneof": [
        {
          "type": "string",
          "maxLength": 90,
          "minLength": 30
        },
        {
          "type": "array",
          "minItems": 1,
          "items": {
            "type": "string",
            "maxLength": 90
          }
        }
      ]
    }
  },
  "properties": {
    "id": {
      "type": "integer",
      "title": "Vulnerability unique id",
      "minimum": 1
    },
    "title": {
      "type": "string",
      "title": "Vulnerability title",
      "minLength": 4,
      "maxLength": 255
    },
    "description": {
      "title": "A very long description for vulnerability",
      "$ref": "#/definitions/multiString"
    },
    "severity": {
      "type": "string",
      "title": "Vulnerability severity",
      "enum": [
        "high",
        "medium",
        "low",
        "informational"
      ]
    },
    "wasc": {
      "type": "array",
      "title": "WASC identifiers",
      "description": "http://projects.webappsec.org/w/page/13246974/Threat%20Classification%20Reference%20Grid",
      "uniqueItems": true,
      "minItems": 1,
      "items": {
        "type": "string",
        "minLength": 1
      }
    },
    "tags": {
      "type": "array",
      "uniqueItems": true,
      "minItems": 1,
      "items": {
        "type": "string",
        "minLength": 2,
        "maxLength": 255
      }
    },
    "cwe": {
      "type": "array",
      "title": "CWE indentifiers",
      "description": "https://cwe.mitre.org/data/index.html",
      "uniqueItems": true,
      "items": {
        "type": "string",
        "minLength": 1
      }
    },
    "owasp_top_10": {
      "type": "object",
      "description": "position in owasp top ten splitted by years",
      "patternProperties": {
        "^[12][0-9]{3}$": {
          "type": "array",
          "minItems": 1,
          "items": {
            "type": "integer",
            "minimum": 1
          }
        }
      },
      "additionalProperties": false
    },
    "fix": {
      "type": "object",
      "properties": {
        "guidance": {
          "$ref": "#/definitions/multiString",
          "title": "A very long text explaining how to fix the vulnerability"
        },
        "effort": {
          "type": "integer",
          "minimum": 0
        }
      },
      "required": [
        "guidance",
        "effort"
      ]
    },
    "references": {
      "type": "array",
      "minItems": 1,      
      "items": {
        "type": "object",
        "properties": {
          "url": {
            "type": "string",
            "format": "uri"
          },
          "title": {
            "type": "string",
            "minLength": 4,
            "maxLength": 255
          }
        },
        "required": [
          "url",
          "title"
        ]
      }
    }
  },
  "required": [
    "id",
    "title",
    "description",
    "severity",
    "fix"
  ]
}

=== vulndb/data/db/28-insecure-cross-domain-policy-allow-http-request-headers-from.json
{
  "id": 28, 
  "title": "Insecure cross-domain policy (allow-http-request-headers-from)", 
  "severity": "low", 
  "description": [
    "The browser security model normally prevents web content from one", 
    "domain from accessing data from another domain. This is commonly known", 
    "as the \"same origin policy\".\n\nURL policy files grant cross-domain", 
    "permissions for reading data. They permit operations that are not", 
    "permitted by default. The URL policy file for Silverlight is located,", 
    "by default, in the root directory of the target server, with the name", 
    "`crossdomain.xml` (for example, at `www.example.com/crossdomain.xml`).", 
    "When a domain is specified in `crossdomain.xml`, the site declares", 
    "that it is willing to allow the operators of any servers in that", 
    "domain to obtain any document on the server where the policy file", 
    "resides.\n\nThe `crossdomain.xml` file deployed on this website opens", 
    "the server to all domains (use of a single asterisk \"*\" as a pure", 
    "wildcard is supported)."
  ], 
  "fix": {
    "effort": 50, 
    "guidance": [
      "Carefully evaluate which sites will be allowed to make cross-domain", 
      "calls.\n\nConsider network topology and any authentication mechanisms", 
      "that will be affected by the configuration or implementation of the", 
      "cross-domain policy."
    ]
  }, 
  "references": [
    {
      "url": "http://blogs.adobe.com/stateofsecurity/2007/07/crossdomain_policy_files_1.html", 
      "title": "Adobe"
    }, 
    {
      "url": "https://www.owasp.org/index.php/Test_Cross_Origin_Resource_Sharing_%28OTG-CLIENT-007%29", 
      "title": "OWASP"
    }
  ]
}

=== vulndb/data/db/10-common-sensitive-file.json
{
  "id": 10, 
  "title": "Common sensitive file", 
  "severity": "low", 
  "description": [
    "Web applications are often made up of multiple files and directories.", 
    "It is possible that over time some files may become unreferenced", 
    "(unused) by the web application and forgotten about by the", 
    "administrator/developer. Because web applications are built using", 
    "common frameworks, they contain common files that can be discovered", 
    "(independent of server).\n\nDuring the initial recon stages of an", 
    "attack, cyber-criminals will attempt to locate unreferenced files in", 
    "the hope that the file will assist in further compromise of the web", 
    "application. To achieve this they will make thousands of requests", 
    "using word lists containing common filenames. The response headers", 
    "from the server will then indicate if the file exists.\n\nThe tool also", 
    "contains a list of common file names which it will attempt to access."
  ], 
  "fix": {
    "effort": 50, 
    "guidance": [
      "If files are unreferenced then they should be removed from the web", 
      "root and/or the application directory.\n\nPreventing access without", 
      "authentication may also be an option and can stop a client from being", 
      "able to view the contents of a file, however it is still likely that", 
      "the directory structure will be able to be discovered.\n\nUsing obscure", 
      "file names is implementing security through obscurity and is not a", 
      "recommended option."
    ]
  }, 
  "tags": [
    "web",
    "common", 
    "path", 
    "file", 
    "discovery"
  ], 
  "references": [
    {
      "url": "http://httpd.apache.org/docs/2.0/mod/mod_access.html", 
      "title": "Apache.org"
    }
  ]
}

=== vulndb/data/db/34-blind-nosql-injection-differential-analysis.json
{
  "id": 34, 
  "title": "Blind NoSQL Injection (differential analysis)", 
  "severity": "high", 
  "description": [
    "A NoSQL injection occurs when a value originating from the client's", 
    "request is used within a NoSQL call without prior sanitisation.\n\nThis", 
    "can allow cyber-criminals to execute arbitrary NoSQL code and thus", 
    "steal data, or use the additional functionality of the database server", 
    "to take control of further server components.\n\nThe tool discovered that", 
    "the affected page and parameter are vulnerable. This injection was", 
    "detected as the tool was able to inject specific NoSQL queries that if", 
    "vulnerable result in the responses for each injection being different.", 
    "This is known as a blind NoSQL injection vulnerability."
  ], 
  "fix": {
    "effort": 50, 
    "guidance": [
      "The most effective remediation against NoSQL injection attacks is to", 
      "ensure that NoSQL API calls are not constructed via string", 
      "concatenation that includes unsanitized data.\n\nSanitization is best", 
      "achieved using existing escaping libraries."
    ]
  }, 
  "cwe": ["89"],
  "tags": [
    "web",
    "nosql", 
    "blind", 
    "injection", 
    "database"
  ], 
  "references": [
    {
      "url": "https://www.owasp.org/index.php/Testing_for_NoSQL_injection", 
      "title": "OWASP"
    }
  ]
}

=== vulndb/data/db/47-blind-sql-injection-timing-attack.json
{
  "id": 47, 
  "title": "Blind SQL Injection (timing attack)", 
  "severity": "high", 
  "description": [
    "Due to the requirement for dynamic content of today's web", 
    "applications, many rely on a database backend to store data that will", 
    "be called upon and processed by the web application (or other", 
    "programs). Web applications retrieve data from the database by using", 
    "Structured Query Language (SQL) queries.\n\nTo meet demands of many", 
    "developers, database servers (such as MSSQL, MySQL, Oracle etc.) have", 
    "additional built-in functionality that can allow extensive control of", 
    "the database and interaction with the host operating system itself.", 
    "An SQL injection occurs when a value originating from the client's", 
    "request is used within a SQL query without prior sanitisation. This", 
    "could allow cyber-criminals to execute arbitrary SQL code and steal", 
    "data or use the additional functionality of the database server to", 
    "take control of more server components.\n\nThe successful exploitation", 
    "of a SQL injection can be devastating to an organisation and is one of", 
    "the most commonly exploited web application vulnerabilities.\n\nThis", 
    "injection was detected as the tool was able to inject specific SQL", 
    "queries, that if vulnerable, result in the responses for each request", 
    "being delayed before being sent by the server. This is known as a", 
    "time-based blind SQL injection vulnerability."
  ], 
  "fix": {
    "effort": 50, 
    "guidance": [
      "The only proven method to prevent against SQL injection attacks while", 
      "still maintaining full application functionality is to use", 
      "parameterized queries (also known as prepared statements). When", 
      "utilising this method of querying the database, any value supplied by", 
      "the client will be handled as a string value rather than part of the", 
      "SQL query.\n\nAdditionally, when utilising parameterized queries, the", 
      "database engine will automatically check to make sure the string being", 
      "used matches that of the column. For example, the database engine will", 
      "check that the user supplied input is an integer if the database", 
      "column is configured to contain integers."
    ]
  }, 
  "tags": [
    "sql", 
    "blind", 
    "timing", 
    "injection", 
    "database"
  ], 
  "references": [
    {
      "url": "http://capec.mitre.org/data/definitions/7.html", 
      "title": "MITRE - CAPEC"
    }, 
    {
      "url": "http://projects.webappsec.org/w/page/13246963/SQL%20Injection", 
      "title": "WASC"
    }, 
    {
      "url": "http://www.w3schools.com/sql/sql_injection.asp", 
      "title": "W3 Schools"
    }, 
    {
      "url": "https://www.owasp.org/index.php/Blind_SQL_Injection", 
      "title": "OWASP"
    }
  ]
}

=== vulndb/data/db/15-directory-listing.json
{
  "id": 15, 
  "title": "Directory listing", 
  "severity": "low", 
  "description": [
    "Web servers permitting directory listing are typically used for", 
    "sharing files.\n\nDirectory listing allows the client to view a simple", 
    "list of all the files and folders hosted on the web server. The client", 
    "is then able to traverse each directory and download the files.", 
    "Cyber-criminals will utilise the presence of directory listing to", 
    "discover sensitive files, download protected content, or even just", 
    "learn how the web application is structured.\n\nThe tool discovered that", 
    "the affected page permits directory listing."
  ], 
  "fix": {
    "effort": 50, 
    "guidance": [
      "Unless the web server is being utilised to share static and", 
      "non-sensitive files, enabling directory listing is considered a poor", 
      "security practice\n\nThis can typically be done with a simple", 
      "configuration change on the server. The steps to disable the directory", 
      "listing will differ depending on the type of server being used (IIS,", 
      "Apache, etc.). If directory listing is required, and permitted, then", 
      "steps should be taken to ensure that the risk of such a configuration", 
      "is reduced.\n\nThese can include:\n",
      "1. Requiring authentication to access affected pages.\n",
      "2. Adding the affected path to the `robots.txt` file to prevent the",
      "directory contents being searchable via search engines.\n",
      "3. Ensuring that sensitive files are not stored within the", 
      "web or document root.\n",
      "4. Removing any files that are not required for the application to",
      "function.\n"
    ]
  }, 
  "tags": [
    "web",
    "path", 
    "directory", 
    "listing", 
    "index"
  ], 
  "references": [
    {
      "url": "http://projects.webappsec.org/w/page/13246922/Directory%20Indexing", 
      "title": "WASC"
    }, 
    {
      "url": "http://cwe.mitre.org/data/definitions/548.html", 
      "title": "CWE-548"
    }
  ]
}

=== vulndb/data/db/67-self-signed-ssl-certificate.json
{
  "id": 67,
  "title": "Self-signed TLS/SSL certificate",
  "severity": "medium", 
  "description": [
    "The server's TLS/SSL certificate is self-signed. Self-signed",
    "certificates are not trusted by browsers and other HTTP clients,",
    "especially because TLS/SSL man-in-the-middle attacks typically use",
    "self-signed certificates to eavesdrop on TLS/SSL connections."
  ], 
  "fix": {
    "effort": 60,
    "guidance": [
      "Create a new TLS/SSL certificate, request a trusted certificate",
      "authority (CA) to sign it and replace the self-signed certificate with",
      "the newly generated one."
    ]
  }, 
  "tags": [
    "web",
    "unencrypted", 
    "tls",
    "ssl"
  ],
  "references": [
    {
      "url": "https://en.wikipedia.org/wiki/Self-signed_certificate",
      "title": "Wikipedia article on self-signed certificates"
    }
  ]
}

=== vulndb/data/db/40-private-ip-address-disclosure.json
{
  "id": 40, 
  "title": "Private IP address disclosure", 
  "severity": "low", 
  "description": [
    "Private, or non-routable, IP addresses are generally used within a", 
    "home or company network and are typically unknown to anyone outside of", 
    "that network.\n\nCyber-criminals will attempt to identify the private IP", 
    "address range being used by their victim, to aid in collecting further", 
    "information that could then lead to a possible compromise.\n\nThe tool", 
    "discovered that the affected page returned a RFC 1918 compliant", 
    "private IP address and therefore could be revealing sensitive", 
    "information.\n\n_This finding typically requires manual verification to", 
    "ensure the context is correct, as any private IP address within the", 
    "HTML body will trigger it."
  ], 
  "fix": {
    "effort": 50, 
    "guidance": [
      "Identifying the context in which the affected page displays a Private", 
      "IP address is necessary.\n\nIf the page is publicly accessible and", 
      "displays the Private IP of the affected server (or supporting", 
      "infrastructure), then measures should be put in place to ensure that", 
      "the IP address is removed from any response."
    ]
  }, 
  "cwe": ["200"],
  "owasp_top_10": {"2013": [6]},
  "references": [
    {
      "url": "http://projects.webappsec.org/w/page/13246936/Information%20Leakage", 
      "title": "WebAppSec"
    }
  ]
}

=== vulndb/data/db/58-dom-based-cross-site-scripting-xss-in-script-context.json
{
  "id": 58, 
  "title": "DOM-based Cross-Site Scripting (XSS) in script context", 
  "severity": "high", 
  "description": [
    "Client-side scripts are used extensively by modern web applications.", 
    "They perform from simple functions (such as the formatting of text) up", 
    "to full\nmanipulation of client-side data and Operating System", 
    "interaction.\n\nUnlike traditional Cross-Site Scripting (XSS), where the", 
    "client is able to inject\nscripts into a request and have the server", 
    "return the script to the client, DOM\nXSS does not require that a", 
    "request be sent to the server and may be abused entirely\nwithin the", 
    "loaded page.\n\nThis occurs when elements of the DOM (known as the", 
    "sources) are able to be\nmanipulated to contain untrusted data, which", 
    "the client-side scripts (known as the\nsinks) use or execute an unsafe", 
    "way.\n\nThe tool has discovered that by modifying the affected DOM", 
    "source, it is possible\nto insert and execute JavaScript code."
  ], 
  "fix": {
    "effort": 50, 
    "guidance": [
      "Client-side document rewriting, redirection, or other sensitive", 
      "action, using\nuntrusted data, should be avoided wherever possible, as", 
      "these may not be inspected\nby server side filtering.\n\nTo remedy DOM", 
      "XSS vulnerabilities where these sensitive document actions must be", 
      "used, it is essential to:\n\n1. Ensure any untrusted data is treated as", 
      "text, as opposed to being interpreted\n    as code or mark-up within", 
      "the page.\n2. Escape untrusted data prior to being used within the", 
      "page. Escaping methods\n    will vary depending on where the untrusted", 
      "data is being used.\n    (See references for details.)\n3. Use", 
      "`document.createElement`, `element.setAttribute`,", 
      "`element.appendChild`,\n    etc. to build dynamic interfaces as opposed", 
      "to HTML rendering methods such as\n    `document.write`,", 
      "`document.writeIn`, `element.innerHTML`, or `element.outerHTML `etc."
    ]
  }, 
  "tags": [
    "xss", 
    "dom", 
    "injection", 
    "script"
  ], 
  "references": [
    {
      "url": "http://projects.webappsec.org/w/page/13246920/Cross%20Site%20Scripting", 
      "title": "WASC"
    }, 
    {
      "url": "https://www.owasp.org/index.php/DOM_based_XSS_Prevention_Cheat_Sheet", 
      "title": "OWASP - Prevention"
    }, 
    {
      "url": "https://www.owasp.org/index.php/DOM_Based_XSS", 
      "title": "OWASP"
    }
  ]
}
