=== vulndb/data/schema.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "type": "object",
  "title": "Vulnerability schema",
  "description": "This schema describes json format for vulnerability",
  "definitions": {
    "multiString": {
      "oneof": [
        {
          "type": "string",
          "maxLength": 90,
          "minLength": 30
        },
        {
          "type": "array",
          "minItems": 1,
          "items": {
            "type": "string",
            "maxLength": 90
          }
        }
      ]
    }
  },
  "properties": {
    "id": {
      "type": "integer",
      "title": "Vulnerability unique id",
      "minimum": 1
    },
    "title": {
      "type": "string",
      "title": "Vulnerability title",
      "minLength": 4,
      "maxLength": 255
    },
    "description": {
      "title": "A very long description for vulnerability",
      "$ref": "#/definitions/multiString"
    },
    "severity": {
      "type": "string",
      "title": "Vulnerability severity",
      "enum": [
        "high",
        "medium",
        "low",
        "informational"
      ]
    },
    "wasc": {
      "type": "array",
      "title": "WASC identifiers",
      "description": "http://projects.webappsec.org/w/page/13246974/Threat%20Classification%20Reference%20Grid",
      "uniqueItems": true,
      "minItems": 1,
      "items": {
        "type": "string",
        "minLength": 1
      }
    },
    "tags": {
      "type": "array",
      "uniqueItems": true,
      "minItems": 1,
      "items": {
        "type": "string",
        "minLength": 2,
        "maxLength": 255
      }
    },
    "cwe": {
      "type": "array",
      "title": "CWE indentifiers",
      "description": "https://cwe.mitre.org/data/index.html",
      "uniqueItems": true,
      "items": {
        "type": "string",
        "minLength": 1
      }
    },
    "owasp_top_10": {
      "type": "object",
      "description": "position in owasp top ten splitted by years",
      "patternProperties": {
        "^[12][0-9]{3}$": {
          "type": "array",
          "minItems": 1,
          "items": {
            "type": "integer",
            "minimum": 1
          }
        }
      },
      "additionalProperties": false
    },
    "fix": {
      "type": "object",
      "properties": {
        "guidance": {
          "$ref": "#/definitions/multiString",
          "title": "A very long text explaining how to fix the vulnerability"
        },
        "effort": {
          "type": "integer",
          "minimum": 0
        }
      },
      "required": [
        "guidance",
        "effort"
      ]
    },
    "references": {
      "type": "array",
      "minItems": 1,      
      "items": {
        "type": "object",
        "properties": {
          "url": {
            "type": "string",
            "format": "uri"
          },
          "title": {
            "type": "string",
            "minLength": 4,
            "maxLength": 255
          }
        },
        "required": [
          "url",
          "title"
        ]
      }
    }
  },
  "required": [
    "id",
    "title",
    "description",
    "severity",
    "fix"
  ]
}

=== vulndb/data/db/31-exposed-localstart-asp-page.json
{
  "id": 31, 
  "title": "Exposed localstart.asp page", 
  "severity": "low", 
  "description": [
    "To restrict access to specific pages on a webserver, developers can", 
    "implement various methods of authentication, therefore only allowing", 
    "access to clients with valid credentials. There are several forms of", 
    "authentication that can be used. The simplest forms of authentication", 
    "are known as 'Basic' and 'Basic Realm'. These methods of", 
    "authentication have several known weaknesses such as being susceptible", 
    "to brute force attacks.\n\nAdditionally, when utilising the NTLM", 
    "mechanism in a windows environment, several disclosures of information", 
    "exist, and any brute force attack occurs against the server's local", 
    "users, or domain users if the web server is a domain member.", 
    "Cyber-criminals will attempt to locate protected pages to gain access", 
    "to them and also perform brute force attacks to discover valid", 
    "credentials.\n\nThe tool discovered the following page requires NTLM", 
    "based basic authentication in order to be accessed."
  ], 
  "fix": {
    "effort": 50, 
    "guidance": [
      "If the pages being protected are not required for the functionality of", 
      "the web application they should be removed, otherwise, it is", 
      "recommended that basic and basic realm authentication are not used to", 
      "protect against pages requiring authentication.\n\nIf NTLM based basic", 
      "authentication must be used, then default server and domain accounts", 
      "such as `administrator` and `root` should be disabled, as these will", 
      "undoubtedly be the first accounts to be targeted in any such attack.", 
      "Additionally, the webserver should not be joined to any corporate", 
      "domain where usernames are readily available (such as from email", 
      "addresses). If the pages are required, and it is possible to remove", 
      "the basic authentication, then a stronger and more resilient", 
      "form-based authentication mechanism should be implemented to protect", 
      "the affected pages."
    ]
  }, 
  "tags": [
    "web",
    "asp", 
    "iis", 
    "server"
  ]
}

=== vulndb/data/db/68-shellshock.json
{
  "id": 68,
  "title": "ShellSock",
  "severity": "high",
  "description": [
    "GNU Bash through 4.3 processes trailing strings after function",
    "definitions in the values of environment variables, which allows remote",
    "attackers to execute arbitrary code via a crafted environment, as",
    "demonstrated by vectors involving the ForceCommand feature in OpenSSH",
    "sshd, the mod_cgi and mod_cgid modules in the Apache HTTP Server, scripts",
    "executed by unspecified DHCP clients, and other situations in which",
    "setting the environment occurs across a privilege boundary from Bash",
    "execution, aka 'ShellShock'"
  ],
  "fix": {
    "effort": 60,
    "guidance": [
      "Upgrade Bash to version 4.3.025 or newer"
    ]
  }, 
  "tags": [
    "bash",
    "shellshock"
  ],
  "references": [
    {
     "url": "https://web.nvd.nist.gov/view/vuln/detail?vulnId=CVE-2014-6271",
     "title": "CVE-2014-6271"
    },
    {
      "url": "https://en.wikipedia.org/wiki/Shellshock_%28software_bug%29",
      "title": "Wikipedia article for Shellshock"
    }
  ]
}

=== vulndb/data/db/63-http-trace.json
{
  "id": 63, 
  "title": "HTTP TRACE", 
  "severity": "medium", 
  "description": [
    "The `TRACE` HTTP method allows a client so send a request to the", 
    "server, and have the same request then send back in the server's", 
    "response. This allows the client to determine if the server is", 
    "receiving the request as expected or if specific parts of the request", 
    "are not arriving as expected. For example incorrect encoding or a load", 
    "balancer has filtered or changed a value. On many default", 
    "installations the `TRACE` method is still enabled.\n\nWhile not", 
    "vulnerable by itself, it does provide a method for cyber-criminals to", 
    "bypass the `HTTPOnly` cookie flag, and therefore could allow a XSS", 
    "attack to successfully access a session token.\n\nThe tool has discovered", 
    "that the affected page permits the HTTP `TRACE` method."
  ], 
  "fix": {
    "effort": 50, 
    "guidance": [
      "The HTTP `TRACE` method is normally not required within production", 
      "sites and should therefore be disabled.\n\nDepending on the function", 
      "being performed by the web application, the risk level can start low", 
      "and increase as more functionality is implemented.\n\nThe remediation is", 
      "typically a very simple configuration change and in most cases will", 
      "not have any negative impact on the server or application."
    ]
  }, 
  "owasp_top_10": {"2013": [5]},
  "tags": [
    "web",
    "xst", 
    "methods", 
    "trace", 
    "server"
  ], 
  "references": [
    {
      "url": "http://capec.mitre.org/data/definitions/107.html", 
      "title": "CAPEC"
    }, 
    {
      "url": "http://www.owasp.org/index.php/Cross_Site_Tracing", 
      "title": "OWASP"
    }
  ]
}

=== vulndb/data/db/74-phishing-vector.json
{
  "id": 74,
  "title": "Phishing vector",
  "severity": "low",
  "description": [
    "The web user interface (UI) does not properly represent critical",
    "information to the user, allowing the information - or its source -",
    "to be obscured or spoofed. This is often a component in phishing attacks.",
    "\n\n",
    "If an attacker can cause the UI to display erroneous data, or to otherwise",
    "convince the user to display information that appears to come from a",
    "trusted source, then the attacker could trick the user into performing the",
    "wrong action. An example of this vulnerability is the possibility to",
    "control the `src` attribute of an iframe tag using a query string",
    "parameter."
  ],
  "fix": {
    "effort": 30,
    "guidance": [
      " * Review the generated HTML source and ensure that none of it's sections",
      "can be used in a UI misrepresentation attack.\n",
      "* Perform strict data validation (e.g. syntax, length, etc.) before",
      "using the user-provided data to render HTML pages.\n"
    ]
  },
  "cwe": ["451"],
  "tags": [
    "web",
    "phishing"
  ],
  "references": [
    {
      "url": "https://www.owasp.org/index.php/Phishing",
      "title": "Phishing - OWASP"
    }
  ]
}

=== vulndb/data/db/19-missing-strict-transport-security-header.json
{
  "id": 19, 
  "title": "Missing 'Strict-Transport-Security' header", 
  "severity": "medium", 
  "description": [
    "The HTTP protocol by itself is clear text, meaning that any data that", 
    "is transmitted via HTTP can be captured and the contents viewed. To", 
    "keep data private and prevent it from being intercepted, HTTP is often", 
    "tunnelled through either Secure Sockets Layer (SSL) or Transport Layer", 
    "Security (TLS). When either of these encryption standards are used, it", 
    "is referred to as HTTPS.\n\nHTTP Strict Transport Security (HSTS) is an", 
    "optional response header that can be configured on the server to", 
    "instruct the browser to only communicate via HTTPS. This will be", 
    "enforced by the browser even if the user requests a HTTP resource on", 
    "the same server.\n\nCyber-criminals will often attempt to compromise", 
    "sensitive information passed from the client to the server using HTTP.", 
    "This can be conducted via various Man-in-The-Middle (MiTM) attacks or", 
    "through network packet captures.\n\nThe tool discovered that the affected", 
    "application is using HTTPS however does not use the HSTS header."
  ], 
  "fix": {
    "effort": 50, 
    "guidance": [
      "Depending on the framework being used the implementation methods will", 
      "vary, however it is advised that the `Strict-Transport-Security`", 
      "header be configured on the server.\n\nOne of the options for this", 
      "header is `max-age`, which is a representation (in milliseconds)", 
      "determining the time in which the client's browser will adhere to the", 
      "header policy.\n\nDepending on the environment and the application this", 
      "time period could be from as low as minutes to as long as days."
    ]
  }, 
  "references": [
    {
      "url": "http://en.wikipedia.org/wiki/HTTP_Strict_Transport_Security", 
      "title": "Wikipedia"
    }, 
    {
      "url": "https://www.owasp.org/index.php/HTTP_Strict_Transport_Security", 
      "title": "OWASP"
    }
  ]
}

=== vulndb/data/db/5-captcha-protected-form.json
{
  "id": 5, 
  "title": "CAPTCHA protected form", 
  "severity": "informational", 
  "description": [
    "To prevent the automated abuse of a page, applications can implement", 
    "what is known as a CAPTCHA.\n\nThese are used to ensure human", 
    "interaction with the application and are often used on forms where the", 
    "application conducts sensitive actions. These typically include user", 
    "registration, or submitting emails via \"Contact Us\" pages etc.", 
    "The tool has flagged this not as a vulnerability, but as a prompt for", 
    "the penetration tester to conduct further manual testing on the", 
    "CAPTCHA function, as The tool cannon audit CAPTCHA protected forms.", 
    "Testing for insecurely implemented CAPTCHA is a manual process, and an", 
    "insecurely implemented CAPTCHA could allow a cyber-criminal a means to", 
    "abuse these sensitive actions."
  ], 
  "fix": {
    "effort": 50, 
    "guidance": [
      "Although no remediation may be required based on this finding alone,", 
      "manual testing should ensure that:\n",
      "1. The server keeps track of CAPTCHA tokens in use and has the token",
      "terminated after its first use or after a period of time. Therefore",
      "preventing replay attacks.\n",
      "2. The CAPTCHA answer is not hidden in plain text within the response", 
      "that is sent to the client.\n",
      "3. The CAPTCHA image should not be weak and easily solved.\n"
    ]
  }
}

=== vulndb/data/db/51-unvalidated-dom-redirect.json
{
  "id": 51, 
  "title": "Unvalidated DOM redirect", 
  "severity": "medium", 
  "description": [
    "Web applications occasionally use DOM input values to store the", 
    "address of the\npage to which the client will be redirected -- for", 
    "example:\n`yoursite.com/#/?redirect=www.yoursite.com/404.asp`\n\nAn", 
    "unvalidated redirect occurs when the client is able to modify the", 
    "affected\nparameter value and thus control the location of the", 
    "redirection.\nFor example, the following URL", 
    "`yoursite.com/#/?redirect=www.anothersite.com`\nwill redirect to", 
    "`www.anothersite.com`.\n\nCyber-criminals will abuse these", 
    "vulnerabilities in social engineering attacks\nto get users to", 
    "unknowingly visit malicious web sites.\n\nThe tool has discovered that", 
    "the web page does not validate the parameter value prior\nto", 
    "redirecting the client to the injected value."
  ], 
  "fix": {
    "effort": 50, 
    "guidance": [
      "The application should ensure that the supplied value for a redirect", 
      "is permitted.\nThis can be achieved by performing whitelisting on the", 
      "parameter value.\n\nThe whitelist should contain a list of pages or", 
      "sites that the application is\npermitted to redirect users to. If the", 
      "supplied value does not match any value\nin the whitelist then the", 
      "server should redirect to a standard error page."
    ]
  }, 
  "tags": [
    "unvalidated", 
    "redirect", 
    "dom", 
    "injection"
  ], 
  "references": [
    {
      "url": "https://www.owasp.org/index.php/Top_10_2010-A10-Unvalidated_Redirects_and_Forwards", 
      "title": "OWASP Top 10 2010"
    }
  ]
}

=== vulndb/data/db/71-reflected-file-download.json
{
  "id": 71,
  "title": "Reflected File Download",
  "severity": "medium",
  "description": [
    "The reflected file download vulnerability is an application weakness",
    "which allows a cyber-criminal to perform advanced social engineering",
    "attacks where an arbitrary executable file is downloaded by the user from",
    "vulnerable site. The contents of the executable file are controlled by",
    "the attacker and are never uploaded to the vulnerable site.",
    "\n\n",
    "This vulnerability, like many other Web attacks, begins by sending a",
    "malicious link to a victim. Unlike other attacks the exploitation finishes",
    "outside of the browser context:",
    "\n\n",
    " 1. The user follows a malicious link to a trusted web site\n",
    " 2. An executable file is downloaded and saved on the user's machine.",
    "All security indicators show that the file is 'hosted' on the trusted web",
    "site\n",
    " 3. The user executes the file which contains shell commands that gain",
    "complete control over the computer."
  ],
  "fix": {
    "effort": 10,
    "guidance": [
      " 1- Explicitly set the `filename` attribute in the Content-disposition",
      "HTTP response header.\n",
      " 2- Perform strict whitelist validation on user input before using it",
      "in the creation of HTTP response bodies\n"
    ]
  }, 
  "tags": [
    "rfd",
    "reflected"
  ],
  "references": [
    {
      "url": "https://www.trustwave.com/Resources/SpiderLabs-Blog/Reflected-File-Download---A-New-Web-Attack-Vector/",
      "title": "Reflected File Download - A New Web Attack Vector"
    }
  ]
}
